version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: anis-mysql
        volumes:
            - ./docker/mysql:/var/lib/mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"   
        environment:
            - MYSQL_ROOT_PASSWORD=help
            - MYSQL_DATABASE=help_student
            - MYSQL_USER=user
            - MYSQL_PASSWORD=help
        ports:
            - 3306:3306

    webserver:
        image: nginx:alpine
        container_name: anis-webserver
       
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80

    php-fpm:
        build: docker/php-fpm
        container_name: anis-php-fpm

        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
